# Generated by Django 5.0.7 on 2024-08-12 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_rename_streamingplatforms_streamingplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Watchlist', to='watchlist_app.streamingplatform'),
            preserve_default=False,
        ),
    ]
